id: IE2462EFF
legacy_id: P000318
ocr_import_info:
  bdrc_scan_id: W23578
  source: bdrc
  ocr_info:
    timestamp: '2020-03-12T16:10:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:17:59.782492+00:00'
last_modified: 2022-09-02 09:18:07.206418
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23578
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23578
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞི་ཁྲོ་ཡེ་ཤེས་མཐོང་གྲོལ།
  author: བསྟན་གཉིས་གླིང་པ།
statistics: null
quality: null
bases:
  I2250:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2250
      total_pages: 290
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2250.txt
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
