id: IE2462EFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T16:10:41+00:00'
last_modified: '2022-06-15T16:22:55.966954+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23578
  title: ཞི་ཁྲོ་ཡེ་ཤེས་མཐོང་གྲོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8CB7:
      image_group_id: I2250
      title: ''
      total_pages: 290
      order: 1
      base_file: 8CB7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
